import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Shukhrat",
      email: "shukhrat@example.com",
      password: bcrypt.hashSync("12345678", 8),
      isAdmin: true,
    },
    {
      name: "Shukhrat",
      email: "zilola@gmail.com",
      password: bcrypt.hashSync("6220969", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Smartch Watch1",
      category: "watch",
      image: "../images/watch.jpg",
      price: 120,
      countInStock: 10,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description:
        "CanMixs Smart Watch Fitness Tracker, Full Touch Screen Sports Watch, CM13 Smartwatch Activity Tracker with Heart Rate Sleep Monitor SMS Call Notification, IP67 Waterproof Pedometer Watch for Men Women",
    },
    {
      name: "Smartch Watch2",
      category: "watch",
      image: "../images/watch2.jpg",
      price: 20,
      countInStock: 12,
      brand: "GRDE",
      rating: 3.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      name: "Cleaner",
      category: "watch",
      image: "../images/cleaner.jpg",
      price: 100,
      countInStock: 15,
      brand: "GRDE",
      rating: 2,
      numReviews: 13,
      description: "CanMixs Smart Watch ",
    },
    {
      name: "Noice canceling headphones",
      category: "headphones",
      image: "../images/headphones.jpg",
      price: 150,
      countInStock: 10,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      name: "Power Bank",
      category: "Power Bank",
      image: "../images/powerBank.jpg",
      price: 120,
      countInStock: 10,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      name: "Hair Straightener",
      category: "Hair",
      image: "../images/Straightener.jpg",
      price: 120,
      countInStock: 110,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      name: "Noice canceling headphones 2 ",
      category: "headphones",
      image: "../images/headphones.jpg",
      price: 150,
      countInStock: 10,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      name: "Smartch Watch3 ",
      category: "watch",
      image: "../images/watch3.jpg",
      price: 20,
      countInStock: 10,
      brand: "GRDE",
      rating: 3,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      name: "Noice canceling headphones1",
      category: "headphones",
      image: "../images/headphones.jpg",
      price: 150,
      countInStock: 10,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
  ],
};

export default data;
