const data = {
  products: [
    {
      _id: "1",
      name: "Smartch Watch",
      category: "watch",
      image: "../images/watch.jpg",
      price: 120,
      countInStock: 10,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description:
        "CanMixs Smart Watch Fitness Tracker, Full Touch Screen Sports Watch, CM13 Smartwatch Activity Tracker with Heart Rate Sleep Monitor SMS Call Notification, IP67 Waterproof Pedometer Watch for Men Women",
    },
    {
      _id: "2",
      name: "Smartch Watch",
      category: "watch",
      image: "../images/watch2.jpg",
      price: 20,
      countInStock: 12,
      brand: "GRDE",
      rating: 3.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      _id: "3",
      name: "Cleaner",
      category: "watch",
      image: "../images/cleaner.jpg",
      price: 100,
      countInStock: 15,
      brand: "GRDE",
      rating: 2,
      numReviews: 13,
      description: "CanMixs Smart Watch ",
    },
    {
      _id: "4",
      name: "Noice canceling headphones",
      category: "headphones",
      image: "../images/headphones.jpg",
      price: 150,
      countInStock: 10,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      _id: "5",
      name: "Power Bank",
      category: "Power Bank",
      image: "../images/powerBank.jpg",
      price: 120,
      countInStock: 0,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      _id: "6",
      name: "Hair Straightener",
      category: "Hair",
      image: "../images/Straightener.jpg",
      price: 120,
      countInStock: 110,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      _id: "7",
      name: "Noice canceling headphones",
      category: "headphones",
      image: "../images/headphones.jpg",
      price: 150,
      countInStock: 10,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      _id: "8",
      name: "Smartch Watch",
      category: "watch",
      image: "../images/watch3.jpg",
      price: 20,
      countInStock: 10,
      brand: "GRDE",
      rating: 3,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
    {
      _id: "9",
      name: "Noice canceling headphones",
      category: "headphones",
      image: "../images/headphones.jpg",
      price: 150,
      countInStock: 10,
      brand: "GRDE",
      rating: 4.5,
      numReviews: 10,
      description: "CanMixs Smart Watch ",
    },
  ],
};

export default data;
